drop table if exists bookmarks;

create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title TEXT UNIQUE NOT NULL,
    description TEXT,
    rating INTEGER,
    url TEXT NOT NULL
);

insert into bookmarks (id, title, url, description, rating)
values
    (1,'Google', 'www.google.com',null,null),
    (2,'Gunnerkrigg', 'www.gunnerkrigg.com',null,null),
    (3,'OWL Sessions', 'www.sessions.thinkful.com',null,null),
    (4,'Replit', 'www.repl.it',null,null),
    (5,'Material', 'www.material.io',null,null),
    (6,'Vercel', 'www.vercel.com',null,null),
    (30, 'queens', 'https://www.youtube.com/watch?v=IdyXKJ8NcNI', 'awesome vid', 4 ),
    (43, 'great site', 'https://courses.thinkful.com/ei-async-apps-v3/checkpoint/3', 'great site to visit', 4 ),
    (32, 'alright site', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises', 'its ok site', 2 ),
    (55, 'maybe ill try', 'https://github.com/thinkful-ei-macaw/address-book-dasha', 'might check out soon', 3),
    (12, 'love it', 'https://lyricsovh.docs.apiary.io/#reference/0/lyrics-of-a-song/search?console=1', 'one of my faves', 5);